### PR TITLE
Don't concat inline (#) comments when inside a value

### LINKED ISSUE #261: Error: Hash in VALUE parsed as comment
Given the following query:

```
INSERT INTO `wp_posts` (`post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_content_filtered`, `post_title`, `post_excerpt`, `post_status`, `post_type`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_parent`, `menu_order`, `post_mime_type`, `guid`) VALUES (1, '2017-08-31 15:15:44', '0000-00-00 00:00:00', '{\n    \"sydney::primary_color\": {\n        \"value\": \"#cde053\",\n        \"type\": \"theme_mod\",\n        \"user_id\": 1\n    }\n}', '', '', '', 'auto-draft', 'customize_changeset', 'closed', 'closed', '', 'c759df8b-32fa-4f56-84c7-f88b8d97a009', '', '', '2017-08-31 15:15:44', '0000-00-00 00:00:00', 0, 0, '', '')
```

The hash char at the beginning of `#cde053` is getting parsed as a comment and breaking the parsing of this query.

I tracked it down to the `concatComments` method of the `PHPSQLLexer` class which doesn't seem to be able to determine that the `#` is inside a VALUE and therefore not a comment.

### PR DESCRIPTION
**Pull request by gilbitron**
Resolves #261

### CODE REVIEW

**Comment by adeelnawaz** [comment]
@gilbitron does it also solve # in column comment? In a create or alter query?

**Comment by gilbitron** [comment]
@adeelnawaz I've not tested that I'm afraid.

**Comment by gilbitron** [comment]
It looks like has actually been resolved by https://github.com/greenlion/PHP-SQL-Parser/commit/c58ac6c3855d5a29f8c9cc5240a79d305986ce3e

**Comment by lifeofguenter** [comment]
any update here?

**Pull request merged**
