### PR TITLE
fix php8.2: definition of property $created

### PR DESCRIPTION
**Pull request by podolinek**
to avoid creating dynamic property

### CODE REVIEW

**Comment by podolinek** [comment]
PHPunit doesn't work for php7.2 and lower and for 7.3 some bugs in tests.

**Comment by mmcev106** [comment]
@podolinek, is this a duplicate of #370?

**Comment by podolinek** [comment]
Hah, duplicate, correct. But tests access to variable $created out of the class, so public required.

**Comment by mmcev106** [comment]
Thanks for the tip!  I just changed it to public.

**Pull request closed without merging**
