### PR TITLE
avoid error with PHP 7.2

### PR DESCRIPTION
**Pull request by nicoder**
Fatal error: Declaration of ReplaceProcessor::process($tokenList)
    must be compatible with
    InsertProcessor::process($tokenList, $token_category = 'INSERT')

### CODE REVIEW

**Comment by PSF1** [comment]
The line 54 must be replaced from:

return parent::process($tokenList, 'REPLACE');

to

return parent::process($tokenList, $token_category);

**Comment by Hoten** [comment]
and the default should be REPLACE not INSERT

I will make a new PR for this

**Comment by PSF1** [comment]
Yes :_ D I found about 4 class with the some problem, all class that extend the same class that this one

**Comment by PSF1** [comment]
In my tests not other need refactoring

**Pull request merged**
